export const TRANSACTION_TYPES = [
  "استخراج مستندات حكومية",
  "استشارة حكومية",
  "بطاقة شخصية",
  "جواز سفر",
  "وثيقة زواج",
  "وثيقة طلاق",
  "شهادة ميلاد",
  "تسجيل مولود بالخارج",
  "تجديد اشتراك نقابة",
  "ملف اعتماد CGFNS",
] as const;

export const GOVERNORATES = [
  "القاهرة",
  "الجيزة",
  "الإسكندرية",
  "الدقهلية",
  "الشرقية",
  "الغربية",
  "المنوفية",
  "البحيرة",
  "القليوبية",
  "الفيوم",
  "بني سويف",
  "المنيا",
  "أسيوط",
  "سوهاج",
  "قنا",
  "الأقصر",
  "أسوان",
  "بورسعيد",
  "السويس",
  "الإسماعيلية",
  "دمياط",
  "البحر الأحمر",
  "الوادي الجديد",
  "مطروح",
  "شمال سيناء",
  "جنوب سيناء",
  "كفر الشيخ",
] as const;

export const STATUS_LABELS: Record<string, { ar: string; color: string }> = {
  pending_review: { ar: "بانتظار المراجعة", color: "bg-amber-100 text-amber-700" },
  accepted_similar: { ar: "مقبولة (معاملة مماثلة)", color: "bg-blue-100 text-blue-700" },
  accepted_agreement: { ar: "مقبولة بعد الاتفاق", color: "bg-indigo-100 text-indigo-700" },
  in_progress: { ar: "قيد التنفيذ", color: "bg-cyan-100 text-cyan-700" },
  completed: { ar: "مكتملة", color: "bg-emerald-100 text-emerald-700" },
  rejected: { ar: "مرفوضة", color: "bg-rose-100 text-rose-700" },
  closed: { ar: "مغلقة/مؤرشفة", color: "bg-slate-200 text-slate-700" },
};
